### ISSUE TITLE
what's the usage of union in flogfs.c?

### ISSUE THREAD

**Issue by oska874** [bnahill/FLogFS#1]
in flogfs, I saw these code:

```
flog_result_t flogfs_format(){
    flog_block_idx_t i;
    flog_block_idx_t first_valid = FLOG_BLOCK_IDX_INVALID;

    union {
        flog_inode_init_sector_t main_buffer;
        flog_inode_init_sector_spare_t spare_buffer;
    };
```

why union has no name ?

**Comment by bnahill** [comment]
Those are anonymous unions, defined in [C11](https://en.wikipedia.org/wiki/C11_%28C_standard_revision%29). It works exactly like if it did have a name, except its members are referred to by their member names rather than union_name.member_name.

It was just to be more concise, but it does add dependency on a more recent toolchain. Make sure you have the "-std=c11" flag in there for GCC.

**Comment by oska874** [comment]
It does not work.I write a simple program like your usage:

```
int main()
{
        union{
                int a;
                char c;
        };
        printf("%x %x\n",a,c);
        return 0;
}
```

Then I compile it `gcc -std=c11 test.c`, the error is same with `gcc test.c`,as below:

```
test.c: In function ‘main’:
test.c:6:16: warning: unnamed struct/union that defines no instances [enabled by default]
                };
                ^
test.c:7:11: warning: implicit declaration of function ‘printf’ [-Wimplicit-function-declaration]
           printf("%x %x\n",a,c);
           ^
test.c:7:11: warning: incompatible implicit declaration of built-in function ‘printf’ [enabled by default]
test.c:7:28: error: ‘a’ undeclared (first use in this function)
           printf("%x %x\n",a,c);
                            ^
test.c:7:28: note: each undeclared identifier is reported only once for each function it appears in
test.c:7:30: error: ‘c’ undeclared (first use in this function)
           printf("%x %x\n",a,c);
```

my gcc is 

```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i686-linux-gnu/4.8/lto-wrapper
Target: i686-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-i386/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-i386 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-i386 --with-arch-directory=i386 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-targets=all --enable-multiarch --disable-werror --with-arch-32=i686 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=i686-linux-gnu --host=i686-linux-gnu --target=i686-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04)
```

Is there any wrong ?

**Comment by bnahill** [comment]
My most recent testing has been pushing this through a C++ compiler which, of course, has a different interpretation of the potential usage of anonymous unions. I'll fix it after work today. Sorry for the trouble.

Still, reading through the C11 spec does suggest to me that it would be valid, but I definitely can't talk the compiler into using it...

-Ben

**Comment by bnahill** [comment]
Alright, try it.

**Comment by oska874** [comment]
As you said , you compile it as CPP, used compiler like g++,or other c++ compiler?
So what does these codes' meaning, share the same memory? But the two structure has no relationship.

**Comment by bnahill** [comment]
For C++, I was using GCC (g++).

That's exactly it. A union will allocate enough space for the largest member but allow that memory to be accessed as any of its member types. I used structs to define and access the flash data structures. Depending on the type of data, I would access the memory via different members of the union. This way, I wouldn't allocate more memory than was necessary or have to explicitly cast everything. There are other ways to do this, but this was easy and very efficient.
